version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/interiit_comments
      - JWT_SECRET=devsecret
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  mongo-data:
